name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: MacOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test-swift

  ubuntu-android:
    name: Ubuntu & Android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: make test-linux
    - name: "Test Swift Package on Android"
      uses: skiptools/swift-android-action@v2
